name = "reframe-toplists"
main = "src/worker.js"
account_id = "485282ffb1d94304113b9aed82ccaa16"
compatibility_date = "2026-04-22"
workers_dev = true

[[kv_namespaces]]
binding = "SESSIONS"
id = "a69bb28406af489f9d249f225c8f4e19"
